### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by ahartikainen** [conda-forge/pocketsphinx-python-feedstock#3]
Hi, do you think Windows build could be possible (maybe linking against conda sphinx?)?

**Comment by BrenBarn** [comment]
Man, +1 to that.  Is this repo active?  I've looked back at it from time to time and still see the Windows build disabled.  As far as I can see there isn't any foolproof way to just do "conda install pocketsphinx" on Windows and it would be really nice if there was!

**Comment by CurtLH** [comment]
@ahartikainen @BrenBarn -- I have not been updating this feedstock lately, and don't really plan to at this time.  But if either of your are interested in being added as maintainers, let me know and I'm happy to make that happen.
